version: 0.0
os: linux
files:
  - source: /build
    destination: /home/grandexchange
  - source: /scripts/check_for_updates.sh
    destination: /home/grandexchange
permissions:
  - group: root
    mode: 755
    object: /home/grandexchange/poll_grandexchange.sh
    user: root
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_tick_stack.sh
      timeout: 300
      runas: root
    - location: scripts/setup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_tick_stack.sh
      timeout: 300
      runas: root
