version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
  build:
    commands:
      - cp -R src $BUILD_DIR
      - pip install -r requirements.txt -t ./$BUILD_DIR
artifacts:
  files:
    - appspec.yml
    - $BUILD_DIR/**/*
    - scripts/*